<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Platforms>x86</Platforms>
	<PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthentiKitTuningApp.Common\AuthentiKitTuningApp.Common.csproj" />
    <ProjectReference Include="..\AuthentiKitTuningApp.Processor\AuthentiKitTuningApp.Processor.csproj" />
  </ItemGroup>

</Project>
